#include <avr/pgmspace.h>
#include <HID-Project.h>

struct Keyname {
  const char* name;
  KeyboardKeycode code;
};

const char KEY_RESERVED_STRING[] PROGMEM = "KEY_RESERVED";
const char KEY_ERROR_ROLLOVER_STRING[] PROGMEM = "KEY_ERROR_ROLLOVER";
const char KEY_POST_FAIL_STRING[] PROGMEM = "KEY_POST_FAIL";
const char KEY_ERROR_UNDEFINED_STRING[] PROGMEM = "KEY_ERROR_UNDEFINED";
const char KEY_A_STRING[] PROGMEM = "KEY_A";
const char KEY_B_STRING[] PROGMEM = "KEY_B";
const char KEY_C_STRING[] PROGMEM = "KEY_C";
const char KEY_D_STRING[] PROGMEM = "KEY_D";
const char KEY_E_STRING[] PROGMEM = "KEY_E";
const char KEY_F_STRING[] PROGMEM = "KEY_F";
const char KEY_G_STRING[] PROGMEM = "KEY_G";
const char KEY_H_STRING[] PROGMEM = "KEY_H";
const char KEY_I_STRING[] PROGMEM = "KEY_I";
const char KEY_J_STRING[] PROGMEM = "KEY_J";
const char KEY_K_STRING[] PROGMEM = "KEY_K";
const char KEY_L_STRING[] PROGMEM = "KEY_L";
const char KEY_M_STRING[] PROGMEM = "KEY_M";
const char KEY_N_STRING[] PROGMEM = "KEY_N";
const char KEY_O_STRING[] PROGMEM = "KEY_O";
const char KEY_P_STRING[] PROGMEM = "KEY_P";
const char KEY_Q_STRING[] PROGMEM = "KEY_Q";
const char KEY_R_STRING[] PROGMEM = "KEY_R";
const char KEY_S_STRING[] PROGMEM = "KEY_S";
const char KEY_T_STRING[] PROGMEM = "KEY_T";
const char KEY_U_STRING[] PROGMEM = "KEY_U";
const char KEY_V_STRING[] PROGMEM = "KEY_V";
const char KEY_W_STRING[] PROGMEM = "KEY_W";
const char KEY_X_STRING[] PROGMEM = "KEY_X";
const char KEY_Y_STRING[] PROGMEM = "KEY_Y";
const char KEY_Z_STRING[] PROGMEM = "KEY_Z";
const char KEY_1_STRING[] PROGMEM = "KEY_1";
const char KEY_2_STRING[] PROGMEM = "KEY_2";
const char KEY_3_STRING[] PROGMEM = "KEY_3";
const char KEY_4_STRING[] PROGMEM = "KEY_4";
const char KEY_5_STRING[] PROGMEM = "KEY_5";
const char KEY_6_STRING[] PROGMEM = "KEY_6";
const char KEY_7_STRING[] PROGMEM = "KEY_7";
const char KEY_8_STRING[] PROGMEM = "KEY_8";
const char KEY_9_STRING[] PROGMEM = "KEY_9";
const char KEY_0_STRING[] PROGMEM = "KEY_0";
const char KEY_ENTER_STRING[] PROGMEM = "KEY_ENTER";
const char KEY_RETURN_STRING[] PROGMEM = "KEY_RETURN";
const char KEY_ESC_STRING[] PROGMEM = "KEY_ESC";
const char KEY_BACKSPACE_STRING[] PROGMEM = "KEY_BACKSPACE";
const char KEY_TAB_STRING[] PROGMEM = "KEY_TAB";
const char KEY_SPACE_STRING[] PROGMEM = "KEY_SPACE";
const char KEY_MINUS_STRING[] PROGMEM = "KEY_MINUS";
const char KEY_EQUAL_STRING[] PROGMEM = "KEY_EQUAL";
const char KEY_LEFT_BRACE_STRING[] PROGMEM = "KEY_LEFT_BRACE";
const char KEY_RIGHT_BRACE_STRING[] PROGMEM = "KEY_RIGHT_BRACE";
const char KEY_BACKSLASH_STRING[] PROGMEM = "KEY_BACKSLASH";
const char KEY_NON_US_NUM_STRING[] PROGMEM = "KEY_NON_US_NUM";
const char KEY_SEMICOLON_STRING[] PROGMEM = "KEY_SEMICOLON";
const char KEY_QUOTE_STRING[] PROGMEM = "KEY_QUOTE";
const char KEY_TILDE_STRING[] PROGMEM = "KEY_TILDE";
const char KEY_COMMA_STRING[] PROGMEM = "KEY_COMMA";
const char KEY_PERIOD_STRING[] PROGMEM = "KEY_PERIOD";
const char KEY_SLASH_STRING[] PROGMEM = "KEY_SLASH";
const char KEY_CAPS_LOCK_STRING[] PROGMEM = "KEY_CAPS_LOCK";
const char KEY_F1_STRING[] PROGMEM = "KEY_F1";
const char KEY_F2_STRING[] PROGMEM = "KEY_F2";
const char KEY_F3_STRING[] PROGMEM = "KEY_F3";
const char KEY_F4_STRING[] PROGMEM = "KEY_F4";
const char KEY_F5_STRING[] PROGMEM = "KEY_F5";
const char KEY_F6_STRING[] PROGMEM = "KEY_F6";
const char KEY_F7_STRING[] PROGMEM = "KEY_F7";
const char KEY_F8_STRING[] PROGMEM = "KEY_F8";
const char KEY_F9_STRING[] PROGMEM = "KEY_F9";
const char KEY_F10_STRING[] PROGMEM = "KEY_F10";
const char KEY_F11_STRING[] PROGMEM = "KEY_F11";
const char KEY_F12_STRING[] PROGMEM = "KEY_F12";
const char KEY_PRINT_STRING[] PROGMEM = "KEY_PRINT";
const char KEY_PRINTSCREEN_STRING[] PROGMEM = "KEY_PRINTSCREEN";
const char KEY_SCROLL_LOCK_STRING[] PROGMEM = "KEY_SCROLL_LOCK";
const char KEY_PAUSE_STRING[] PROGMEM = "KEY_PAUSE";
const char KEY_INSERT_STRING[] PROGMEM = "KEY_INSERT";
const char KEY_HOME_STRING[] PROGMEM = "KEY_HOME";
const char KEY_PAGE_UP_STRING[] PROGMEM = "KEY_PAGE_UP";
const char KEY_DELETE_STRING[] PROGMEM = "KEY_DELETE";
const char KEY_END_STRING[] PROGMEM = "KEY_END";
const char KEY_PAGE_DOWN_STRING[] PROGMEM = "KEY_PAGE_DOWN";
const char KEY_RIGHT_ARROW_STRING[] PROGMEM = "KEY_RIGHT_ARROW";
const char KEY_LEFT_ARROW_STRING[] PROGMEM = "KEY_LEFT_ARROW";
const char KEY_DOWN_ARROW_STRING[] PROGMEM = "KEY_DOWN_ARROW";
const char KEY_UP_ARROW_STRING[] PROGMEM = "KEY_UP_ARROW";
const char KEY_RIGHT_STRING[] PROGMEM = "KEY_RIGHT";
const char KEY_LEFT_STRING[] PROGMEM = "KEY_LEFT";
const char KEY_DOWN_STRING[] PROGMEM = "KEY_DOWN";
const char KEY_UP_STRING[] PROGMEM = "KEY_UP";
const char KEY_NUM_LOCK_STRING[] PROGMEM = "KEY_NUM_LOCK";
const char KEYPAD_DIVIDE_STRING[] PROGMEM = "KEYPAD_DIVIDE";
const char KEYPAD_MULTIPLY_STRING[] PROGMEM = "KEYPAD_MULTIPLY";
const char KEYPAD_SUBTRACT_STRING[] PROGMEM = "KEYPAD_SUBTRACT";
const char KEYPAD_ADD_STRING[] PROGMEM = "KEYPAD_ADD";
const char KEYPAD_ENTER_STRING[] PROGMEM = "KEYPAD_ENTER";
const char KEYPAD_1_STRING[] PROGMEM = "KEYPAD_1";
const char KEYPAD_2_STRING[] PROGMEM = "KEYPAD_2";
const char KEYPAD_3_STRING[] PROGMEM = "KEYPAD_3";
const char KEYPAD_4_STRING[] PROGMEM = "KEYPAD_4";
const char KEYPAD_5_STRING[] PROGMEM = "KEYPAD_5";
const char KEYPAD_6_STRING[] PROGMEM = "KEYPAD_6";
const char KEYPAD_7_STRING[] PROGMEM = "KEYPAD_7";
const char KEYPAD_8_STRING[] PROGMEM = "KEYPAD_8";
const char KEYPAD_9_STRING[] PROGMEM = "KEYPAD_9";
const char KEYPAD_0_STRING[] PROGMEM = "KEYPAD_0";
const char KEYPAD_DOT_STRING[] PROGMEM = "KEYPAD_DOT";
const char KEY_NON_US_STRING[] PROGMEM = "KEY_NON_US";
const char KEY_APPLICATION_STRING[] PROGMEM = "KEY_APPLICATION";
const char KEY_MENU_STRING[] PROGMEM = "KEY_MENU";

const char* const ALL_KEYNAMES[] PROGMEM = {
  KEY_RESERVED_STRING,
  KEY_ERROR_ROLLOVER_STRING,
  KEY_POST_FAIL_STRING,
  KEY_ERROR_UNDEFINED_STRING,
  KEY_A_STRING,
  KEY_B_STRING,
  KEY_C_STRING,
  KEY_D_STRING,
  KEY_E_STRING,
  KEY_F_STRING,
  KEY_G_STRING,
  KEY_H_STRING,
  KEY_I_STRING,
  KEY_J_STRING,
  KEY_K_STRING,
  KEY_L_STRING,
  KEY_M_STRING,
  KEY_N_STRING,
  KEY_O_STRING,
  KEY_P_STRING,
  KEY_Q_STRING,
  KEY_R_STRING,
  KEY_S_STRING,
  KEY_T_STRING,
  KEY_U_STRING,
  KEY_V_STRING,
  KEY_W_STRING,
  KEY_X_STRING,
  KEY_Y_STRING,
  KEY_Z_STRING,
  KEY_1_STRING,
  KEY_2_STRING,
  KEY_3_STRING,
  KEY_4_STRING,
  KEY_5_STRING,
  KEY_6_STRING,
  KEY_7_STRING,
  KEY_8_STRING,
  KEY_9_STRING,
  KEY_0_STRING,
  KEY_ENTER_STRING,
  KEY_RETURN_STRING,
  KEY_ESC_STRING,
  KEY_BACKSPACE_STRING,
  KEY_TAB_STRING,
  KEY_SPACE_STRING,
  KEY_MINUS_STRING,
  KEY_EQUAL_STRING,
  KEY_LEFT_BRACE_STRING,
  KEY_RIGHT_BRACE_STRING,
  KEY_BACKSLASH_STRING,
  KEY_NON_US_NUM_STRING,
  KEY_SEMICOLON_STRING,
  KEY_QUOTE_STRING,
  KEY_TILDE_STRING,
  KEY_COMMA_STRING,
  KEY_PERIOD_STRING,
  KEY_SLASH_STRING,
  KEY_CAPS_LOCK_STRING,
  KEY_F1_STRING,
  KEY_F2_STRING,
  KEY_F3_STRING,
  KEY_F4_STRING,
  KEY_F5_STRING,
  KEY_F6_STRING,
  KEY_F7_STRING,
  KEY_F8_STRING,
  KEY_F9_STRING,
  KEY_F10_STRING,
  KEY_F11_STRING,
  KEY_F12_STRING,
  KEY_PRINT_STRING,
  KEY_PRINTSCREEN_STRING,
  KEY_SCROLL_LOCK_STRING,
  KEY_PAUSE_STRING,
  KEY_INSERT_STRING,
  KEY_HOME_STRING,
  KEY_PAGE_UP_STRING,
  KEY_DELETE_STRING,
  KEY_END_STRING,
  KEY_PAGE_DOWN_STRING,
  KEY_RIGHT_ARROW_STRING,
  KEY_LEFT_ARROW_STRING,
  KEY_DOWN_ARROW_STRING,
  KEY_UP_ARROW_STRING,
  KEY_RIGHT_STRING,
  KEY_LEFT_STRING,
  KEY_DOWN_STRING,
  KEY_UP_STRING,
  KEY_NUM_LOCK_STRING,
  KEYPAD_DIVIDE_STRING,
  KEYPAD_MULTIPLY_STRING,
  KEYPAD_SUBTRACT_STRING,
  KEYPAD_ADD_STRING,
  KEYPAD_ENTER_STRING,
  KEYPAD_1_STRING,
  KEYPAD_2_STRING,
  KEYPAD_3_STRING,
  KEYPAD_4_STRING,
  KEYPAD_5_STRING,
  KEYPAD_6_STRING,
  KEYPAD_7_STRING,
  KEYPAD_8_STRING,
  KEYPAD_9_STRING,
  KEYPAD_0_STRING,
  KEYPAD_DOT_STRING,
  KEY_NON_US_STRING,
  KEY_APPLICATION_STRING,
  KEY_MENU_STRING,
};

struct Keyname const KEYNAMES[] PROGMEM = {
{ KEY_RESERVED_STRING, KEY_RESERVED },
{ KEY_ERROR_ROLLOVER_STRING, KEY_ERROR_ROLLOVER },
{ KEY_POST_FAIL_STRING, KEY_POST_FAIL },
{ KEY_ERROR_UNDEFINED_STRING, KEY_ERROR_UNDEFINED },
{ KEY_A_STRING, KEY_A },
{ KEY_B_STRING, KEY_B },
{ KEY_C_STRING, KEY_C },
{ KEY_D_STRING, KEY_D },
{ KEY_E_STRING, KEY_E },
{ KEY_F_STRING, KEY_F },
{ KEY_G_STRING, KEY_G },
{ KEY_H_STRING, KEY_H },
{ KEY_I_STRING, KEY_I },
{ KEY_J_STRING, KEY_J },
{ KEY_K_STRING, KEY_K },
{ KEY_L_STRING, KEY_L },
{ KEY_M_STRING, KEY_M },
{ KEY_N_STRING, KEY_N },
{ KEY_O_STRING, KEY_O },
{ KEY_P_STRING, KEY_P },
{ KEY_Q_STRING, KEY_Q },
{ KEY_R_STRING, KEY_R },
{ KEY_S_STRING, KEY_S },
{ KEY_T_STRING, KEY_T },
{ KEY_U_STRING, KEY_U },
{ KEY_V_STRING, KEY_V },
{ KEY_W_STRING, KEY_W },
{ KEY_X_STRING, KEY_X },
{ KEY_Y_STRING, KEY_Y },
{ KEY_Z_STRING, KEY_Z },
{ KEY_1_STRING, KEY_1 },
{ KEY_2_STRING, KEY_2 },
{ KEY_3_STRING, KEY_3 },
{ KEY_4_STRING, KEY_4 },
{ KEY_5_STRING, KEY_5 },
{ KEY_6_STRING, KEY_6 },
{ KEY_7_STRING, KEY_7 },
{ KEY_8_STRING, KEY_8 },
{ KEY_9_STRING, KEY_9 },
{ KEY_0_STRING, KEY_0 },
{ KEY_ENTER_STRING, KEY_ENTER },
{ KEY_RETURN_STRING, KEY_RETURN },
{ KEY_ESC_STRING, KEY_ESC },
{ KEY_BACKSPACE_STRING, KEY_BACKSPACE },
{ KEY_TAB_STRING, KEY_TAB },
{ KEY_SPACE_STRING, KEY_SPACE },
{ KEY_MINUS_STRING, KEY_MINUS },
{ KEY_EQUAL_STRING, KEY_EQUAL },
{ KEY_LEFT_BRACE_STRING, KEY_LEFT_BRACE },
{ KEY_RIGHT_BRACE_STRING, KEY_RIGHT_BRACE },
{ KEY_BACKSLASH_STRING, KEY_BACKSLASH },
{ KEY_NON_US_NUM_STRING, KEY_NON_US_NUM },
{ KEY_SEMICOLON_STRING, KEY_SEMICOLON },
{ KEY_QUOTE_STRING, KEY_QUOTE },
{ KEY_TILDE_STRING, KEY_TILDE },
{ KEY_COMMA_STRING, KEY_COMMA },
{ KEY_PERIOD_STRING, KEY_PERIOD },
{ KEY_SLASH_STRING, KEY_SLASH },
{ KEY_CAPS_LOCK_STRING, KEY_CAPS_LOCK },
{ KEY_F1_STRING, KEY_F1 },
{ KEY_F2_STRING, KEY_F2 },
{ KEY_F3_STRING, KEY_F3 },
{ KEY_F4_STRING, KEY_F4 },
{ KEY_F5_STRING, KEY_F5 },
{ KEY_F6_STRING, KEY_F6 },
{ KEY_F7_STRING, KEY_F7 },
{ KEY_F8_STRING, KEY_F8 },
{ KEY_F9_STRING, KEY_F9 },
{ KEY_F10_STRING, KEY_F10 },
{ KEY_F11_STRING, KEY_F11 },
{ KEY_F12_STRING, KEY_F12 },
{ KEY_PRINT_STRING, KEY_PRINT },
{ KEY_PRINTSCREEN_STRING, KEY_PRINTSCREEN },
{ KEY_SCROLL_LOCK_STRING, KEY_SCROLL_LOCK },
{ KEY_PAUSE_STRING, KEY_PAUSE },
{ KEY_INSERT_STRING, KEY_INSERT },
{ KEY_HOME_STRING, KEY_HOME },
{ KEY_PAGE_UP_STRING, KEY_PAGE_UP },
{ KEY_DELETE_STRING, KEY_DELETE },
{ KEY_END_STRING, KEY_END },
{ KEY_PAGE_DOWN_STRING, KEY_PAGE_DOWN },
{ KEY_RIGHT_ARROW_STRING, KEY_RIGHT_ARROW },
{ KEY_LEFT_ARROW_STRING, KEY_LEFT_ARROW },
{ KEY_DOWN_ARROW_STRING, KEY_DOWN_ARROW },
{ KEY_UP_ARROW_STRING, KEY_UP_ARROW },
{ KEY_RIGHT_STRING, KEY_RIGHT },
{ KEY_LEFT_STRING, KEY_LEFT },
{ KEY_DOWN_STRING, KEY_DOWN },
{ KEY_UP_STRING, KEY_UP },
{ KEY_NUM_LOCK_STRING, KEY_NUM_LOCK },
{ KEYPAD_DIVIDE_STRING, KEYPAD_DIVIDE },
{ KEYPAD_MULTIPLY_STRING, KEYPAD_MULTIPLY },
{ KEYPAD_SUBTRACT_STRING, KEYPAD_SUBTRACT },
{ KEYPAD_ADD_STRING, KEYPAD_ADD },
{ KEYPAD_ENTER_STRING, KEYPAD_ENTER },
{ KEYPAD_1_STRING, KEYPAD_1 },
{ KEYPAD_2_STRING, KEYPAD_2 },
{ KEYPAD_3_STRING, KEYPAD_3 },
{ KEYPAD_4_STRING, KEYPAD_4 },
{ KEYPAD_5_STRING, KEYPAD_5 },
{ KEYPAD_6_STRING, KEYPAD_6 },
{ KEYPAD_7_STRING, KEYPAD_7 },
{ KEYPAD_8_STRING, KEYPAD_8 },
{ KEYPAD_9_STRING, KEYPAD_9 },
{ KEYPAD_0_STRING, KEYPAD_0 },
{ KEYPAD_DOT_STRING, KEYPAD_DOT },
{ KEY_NON_US_STRING, KEY_NON_US },
{ KEY_APPLICATION_STRING, KEY_APPLICATION },
{ KEY_MENU_STRING, KEY_MENU },
};

KeyboardKeycode getKeycodeFromName(char*);

void getNameFromKeycode(byte, char*);

void printKeynames();